version: '3.7'

services:

    app:
        restart: on-failure
        build:
            context: ./
            dockerfile: docker/Dockerfile
        image: platon
        container_name: platon_app
        command: npm run start:app -- --host 0.0.0.0 --disable-host-check
        ports:
            - 4200:4200
        networks:
            - platon-network

    api:
        restart: on-failure
        build:
            context: ./
            dockerfile: docker/Dockerfile
        image: platon
        container_name: platon_api
        command: npm run start:api
        ports:
            - 3333:3333
        networks:
            - platon-network

networks:
    platon-network:
        driver: bridge
